/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { createAppContainer, createStackNavigator } from "react-navigation";

// Screens
import LoginScreen from "./Screen/LoginScreen";
import Home from "./Screen/Home";
import Profile from "./Screen/Profile";
import ChangePwd from "./Screen/ChangePwd";

/* START MY SCREENS IMPORT */

import BatchEdit from "./Screen/BatchEdit";
import BatchList from "./Screen/BatchList";
import BranchEdit from "./Screen/BranchEdit";
import BranchList from "./Screen/BranchList";
import SemesterEdit from "./Screen/SemesterEdit";
import SemesterList from "./Screen/SemesterList";
import StudentEdit from "./Screen/StudentEdit";
import StudentList from "./Screen/StudentList";
import ProfessorEdit from "./Screen/ProfessorEdit";
import ProfessorList from "./Screen/ProfessorList";
import ResultEdit from "./Screen/ResultEdit";
import ResultList from "./Screen/ResultList";
import SubjectEdit from "./Screen/SubjectEdit";
import SubjectList from "./Screen/SubjectList";

/* END MY SCREENS IMPORT */

class AppContainer extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const AppNavigator = createStackNavigator(
      {
        Login: { screen: LoginScreen },
        Home: { screen: Home },
        Profile: { screen: Profile },
        ChangePwd: { screen: ChangePwd },

        /* START MY SCREENS */

    BatchEdit: { screen: BatchEdit },
    BatchList: { screen: BatchList },
    BranchEdit: { screen: BranchEdit },
    BranchList: { screen: BranchList },
    SemesterEdit: { screen: SemesterEdit },
    SemesterList: { screen: SemesterList },
    StudentEdit: { screen: StudentEdit },
    StudentList: { screen: StudentList },
    ProfessorEdit: { screen: ProfessorEdit },
    ProfessorList: { screen: ProfessorList },
    ResultEdit: { screen: ResultEdit },
    ResultList: { screen: ResultList },
    SubjectEdit: { screen: SubjectEdit },
    SubjectList: { screen: SubjectList },
    
     /* END MY SCREENS */
      },
      {
        initialRouteName: this.props.user ? "Home" : "Login",
        headerMode: "none"
      }
    );

    const AppContainerRouter = createAppContainer(AppNavigator);

    return <AppContainerRouter />;
  }
}

export default AppContainer;
