/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import BranchActions from "../redux/actions/BranchActions";
import SemesterActions from "../redux/actions/SemesterActions";
import StudentActions from "../redux/actions/StudentActions";
import ResultActions from "../redux/actions/ResultActions";
import SubjectActions from "../redux/actions/SubjectActions";

// END IMPORT ACTIONS

/** APIs

* actionsBranch.create
*	@description CRUD ACTION create
*
* actionsBranch.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsBranch.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsSemester.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsStudent.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsResult.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*
* actionsSubject.findBybranch
*	@description CRUD ACTION findBybranch
*	@param Objectid key - Id of model to search for
*

**/


class BranchEdit extends Component {
  
  // Init branch
  constructor(props) {
    super(props);
    this.state = {
      branch: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsBranch.loadBranch(itemId);
        this.props.actionsSubject.findBybranch(itemId);
        this.props.actionsResult.findBybranch(itemId);
        this.props.actionsStudent.findBybranch(itemId);
        this.props.actionsSemester.findBybranch(itemId);
      } else {
        this.setState({
          branch: {}
        });
      }
      
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      branch: {}
    });
    this.props.actionsBranch.reset();
  }

  // Insert props branch in state
  componentWillReceiveProps(props) {
    this.setState({
      branch: props.branch
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.branch._id) {
      // Edit
      this.props.actionsBranch.saveBranch(this.state.branch).then(data => {
        this.props.navigation.navigate("BranchList");
      });
    } else {
      // Create
      this.props.actionsBranch.createBranch(this.state.branch).then(data => {
        this.props.navigation.navigate("BranchList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Branch</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel>
              <Label>
                Name
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.branch, { name: value }))
                }
                value={this.state.branch.name && this.state.branch.name.toString()}
              />
            </Item>
          

          {/* RELATIONS */}
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with subject */}

          
          {/* External relation with result */}

          
          {/* External relation with Student */}

          
          {/* External relation with Semester */}

          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsBranch: bindActionCreators(BranchActions, dispatch),
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsResult: bindActionCreators(ResultActions, dispatch),
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
  };
};

// Validate types
BranchEdit.propTypes = { 
  actionsBranch: PropTypes.object.isRequired,
  actionsSemester: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
  actionsResult: PropTypes.object.isRequired,
  actionsSubject: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    branch: state.BranchEditReducer.branch,
    listSubject: state.BranchEditReducer.listSubject,
    listResult: state.BranchEditReducer.listResult,
    listStudent: state.BranchEditReducer.listStudent,
    listSemester: state.BranchEditReducer.listSemester
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BranchEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
