/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import SectionedMultiSelect from "react-native-sectioned-multi-select";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
  Picker,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import ProfessorActions from "../redux/actions/ProfessorActions";

// END IMPORT ACTIONS

/** APIs

* actionsProfessor.create
*	@description CRUD ACTION create
*
* actionsProfessor.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsProfessor.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/


class ProfessorEdit extends Component {
  
  // Init professor
  constructor(props) {
    super(props);
    this.state = {
      professor: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsProfessor.loadProfessor(itemId);
        this.props.actionsStudent.findBy_teacher(itemId);
      } else {
        this.setState({
          professor: {}
        });
      }
      
      this.props.actionsBatch.loadBatchList();
      this.props.actionsStudent.loadStudentList();
      this.props.actionsSemester.loadSemesterList();
      this.props.actionsSubject.loadSubjectList();
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      professor: {}
    });
    this.props.actionsProfessor.reset();
  }

  // Insert props professor in state
  componentWillReceiveProps(props) {
    this.setState({
      professor: props.professor
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.professor._id) {
      // Edit
      this.props.actionsProfessor.saveProfessor(this.state.professor).then(data => {
        this.props.navigation.navigate("ProfessorList");
      });
    } else {
      // Create
      this.props.actionsProfessor.createProfessor(this.state.professor).then(data => {
        this.props.navigation.navigate("ProfessorList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Professor</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel>
              <Label>
                Address
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.professor, { address: value }))
                }
                value={this.state.professor.address && this.state.professor.address.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Contact_no
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.professor, { contact_no: value }))
                }
                value={this.state.professor.contact_no && this.state.professor.contact_no.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Email
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.professor, { email: value }))
                }
                value={this.state.professor.email && this.state.professor.email.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                F_name
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.professor, { f_name: value }))
                }
                value={this.state.professor.f_name && this.state.professor.f_name.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                L_name
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.professor, { l_name: value }))
                }
                value={this.state.professor.l_name && this.state.professor.l_name.toString()}
              />
            </Item>
          

          {/* RELATIONS */}
          
          {/* Relation 1:m _batch with Batch */}
          
          <Item stackedLabel>
            <Label >
              _batch
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.professor._batch }
              value={this.state.professor._batch }
              onValueChange={value =>
                this.setState(Object.assign(this.state.professor, { _batch: value }))
              }
            >
              {this.props.listBatch &&
                this.props.listBatch.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          
          {/* Relation 1:m _student with Student */}
          
          <Item stackedLabel>
            <Label >
              _student
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.professor._student }
              value={this.state.professor._student }
              onValueChange={value =>
                this.setState(Object.assign(this.state.professor, { _student: value }))
              }
            >
              {this.props.listStudent &&
                this.props.listStudent.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          
          {/* Relation m:m _student with Semester */}
          
          <Item stackedLabel>              
            <Label >
              _student
            </Label>
            <SectionedMultiSelect
              items={this.props.listSemester }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.professor, { _student: value }))
              }
              selectedItems={this.state.professor._student }
            />
          </Item>
          
          
          {/* Relation 1:m _subject with subject */}
          
          <Item stackedLabel>
            <Label >
              _subject
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.professor._subject }
              value={this.state.professor._subject }
              onValueChange={value =>
                this.setState(Object.assign(this.state.professor, { _subject: value }))
              }
            >
              {this.props.listSubject &&
                this.props.listSubject.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Student */}

          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
  };
};

// Validate types
ProfessorEdit.propTypes = { 
  actionsProfessor: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    professor: state.ProfessorEditReducer.professor,
    listBatch: state.ProfessorEditReducer.listBatch,
    listStudent: state.ProfessorEditReducer.listStudent,
    listSemester: state.ProfessorEditReducer.listSemester,
    listSubject: state.ProfessorEditReducer.listSubject,
    listStudent: state.ProfessorEditReducer.listStudent
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ProfessorEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
