/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import SectionedMultiSelect from "react-native-sectioned-multi-select";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
  Picker,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import SemesterActions from "../redux/actions/SemesterActions";
import ProfessorActions from "../redux/actions/ProfessorActions";
import BranchActions from "../redux/actions/BranchActions";
import ResultActions from "../redux/actions/ResultActions";
import SubjectActions from "../redux/actions/SubjectActions";
import StudentActions from "../redux/actions/StudentActions";

// END IMPORT ACTIONS

/** APIs

* actionsSemester.create
*	@description CRUD ACTION create
*
* actionsSemester.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsSemester.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsProfessor.findBy_student
*	@description CRUD ACTION findBy_student
*	@param Objectid key - Id of model to search for
*
* actionsBranch.list
*	@description CRUD ACTION list
*
* actionsResult.list
*	@description CRUD ACTION list
*
* actionsSubject.list
*	@description CRUD ACTION list
*
* actionsStudent.findBysemester
*	@description CRUD ACTION findBysemester
*	@param Objectid key - Id of model to search for
*
* actionsResult.findBysem
*	@description CRUD ACTION findBysem
*	@param Objectid key - Id of model to search for
*
* actionsSubject.findBysemester
*	@description CRUD ACTION findBysemester
*	@param Objectid key - Id of model to search for
*

**/


class SemesterEdit extends Component {
  
  // Init semester
  constructor(props) {
    super(props);
    this.state = {
      semester: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsSemester.loadSemester(itemId);
        this.props.actionsProfessor.findBy_student(itemId);
        this.props.actionsResult.findBysem(itemId);
        this.props.actionsSubject.findBysemester(itemId);
        this.props.actionsStudent.findBysemester(itemId);
      } else {
        this.setState({
          semester: {}
        });
      }
      
      this.props.actionsBranch.loadBranchList();
      this.props.actionsResult.loadResultList();
      this.props.actionsSubject.loadSubjectList();
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      semester: {}
    });
    this.props.actionsSemester.reset();
  }

  // Insert props semester in state
  componentWillReceiveProps(props) {
    this.setState({
      semester: props.semester
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.semester._id) {
      // Edit
      this.props.actionsSemester.saveSemester(this.state.semester).then(data => {
        this.props.navigation.navigate("SemesterList");
      });
    } else {
      // Create
      this.props.actionsSemester.createSemester(this.state.semester).then(data => {
        this.props.navigation.navigate("SemesterList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Semester</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel>
              <Label>
                Semester
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.semester, { semester: value }))
                }
                value={this.state.semester.semester && this.state.semester.semester.toString()}
              />
            </Item>
          

          {/* RELATIONS */}
          
          {/* Relation 1:m branch with Branch */}
          
          <Item stackedLabel>
            <Label >
              Branch
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.semester.branch }
              value={this.state.semester.branch }
              onValueChange={value =>
                this.setState(Object.assign(this.state.semester, { branch: value }))
              }
            >
              {this.props.listBranch &&
                this.props.listBranch.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          
          {/* Relation m:m result with result */}
          
          <Item stackedLabel>              
            <Label >
              Result
            </Label>
            <SectionedMultiSelect
              items={this.props.listResult }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.semester, { result: value }))
              }
              selectedItems={this.state.semester.result }
            />
          </Item>
          
          
          {/* Relation 1:m semester with subject */}
          
          <Item stackedLabel>
            <Label >
              Semester
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.semester.semester }
              value={this.state.semester.semester }
              onValueChange={value =>
                this.setState(Object.assign(this.state.semester, { semester: value }))
              }
            >
              {this.props.listSubject &&
                this.props.listSubject.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with professor */}

          
          {/* External relation with result */}

          
          {/* External relation with subject */}

          
          {/* External relation with Student */}

          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
    actionsBranch: bindActionCreators(BranchActions, dispatch),
    actionsResult: bindActionCreators(ResultActions, dispatch),
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
  };
};

// Validate types
SemesterEdit.propTypes = { 
  actionsSemester: PropTypes.object.isRequired,
  actionsProfessor: PropTypes.object.isRequired,
  actionsBranch: PropTypes.object.isRequired,
  actionsResult: PropTypes.object.isRequired,
  actionsSubject: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    semester: state.SemesterEditReducer.semester,
    listBranch: state.SemesterEditReducer.listBranch,
    listResult: state.SemesterEditReducer.listResult,
    listSubject: state.SemesterEditReducer.listSubject,
    listProfessor: state.SemesterEditReducer.listProfessor,
    listResult: state.SemesterEditReducer.listResult,
    listSubject: state.SemesterEditReducer.listSubject,
    listStudent: state.SemesterEditReducer.listStudent
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SemesterEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
