/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import SectionedMultiSelect from "react-native-sectioned-multi-select";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
  DatePicker,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import StudentActions from "../redux/actions/StudentActions";

// END IMPORT ACTIONS

/** APIs

* actionsStudent.create
*	@description CRUD ACTION create
*
* actionsStudent.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsStudent.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsUser.list
*	@description CRUD ACTION list
*

**/


class StudentEdit extends Component {
  
  // Init student
  constructor(props) {
    super(props);
    this.state = {
      student: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsStudent.loadStudent(itemId);
      } else {
        this.setState({
          student: {}
        });
      }
      
      this.props.actionsUser.loadUserList();
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      student: {}
    });
    this.props.actionsStudent.reset();
  }

  // Insert props student in state
  componentWillReceiveProps(props) {
    this.setState({
      student: props.student
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.student._id) {
      // Edit
      this.props.actionsStudent.saveStudent(this.state.student).then(data => {
        this.props.navigation.navigate("StudentList");
      });
    } else {
      // Create
      this.props.actionsStudent.createStudent(this.state.student).then(data => {
        this.props.navigation.navigate("StudentList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Student</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel>
              <Label>
                Address
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.student, { Address: value }))
                }
                value={this.state.student.Address && this.state.student.Address.toString()}
              />
            </Item>
          
            <Item stackedLabel>
              <Label>
                Birthdate
              </Label>
              <DatePicker
                placeHolderText="Select a date"
                defaultDate={this.state.student.Birthdate }
                onDateChange={value => 
                  this.setState(Object.assign(this.state.student, { Birthdate: value }))
                }
              />
            </Item>
            
            
            <Item floatingLabel>
              <Label>
                Branch
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.student, { Branch: value }))
                }
                value={this.state.student.Branch && this.state.student.Branch.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Gender
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.student, { Gender: value }))
                }
                value={this.state.student.Gender && this.state.student.Gender.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Name
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.student, { Name: value }))
                }
                value={this.state.student.Name && this.state.student.Name.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Phonenumber
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.student, { Phonenumber: value }))
                }
                value={this.state.student.Phonenumber && this.state.student.Phonenumber.toString()}
              />
            </Item>
          

          {/* RELATIONS */}
          
          {/* Relation m:m Tid with User */}
          
          <Item stackedLabel>              
            <Label >
              Tid
            </Label>
            <SectionedMultiSelect
              items={this.props.listUser }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.student, { Tid: value }))
              }
              selectedItems={this.state.student.Tid }
            />
          </Item>
          
          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsStudent: bindActionCreators(StudentActions, dispatch),
  };
};

// Validate types
StudentEdit.propTypes = { 
  actionsStudent: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    student: state.StudentEditReducer.student,
    listUser: state.StudentEditReducer.listUser
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(StudentEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
