/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e5c1e0652a8e9561a0d2dba
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import SectionedMultiSelect from "react-native-sectioned-multi-select";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import SubjectActions from "../redux/actions/SubjectActions";
import StudentActions from "../redux/actions/StudentActions";
import ProfessorActions from "../redux/actions/ProfessorActions";
import SemesterActions from "../redux/actions/SemesterActions";
import BranchActions from "../redux/actions/BranchActions";

// END IMPORT ACTIONS

/** APIs

* actionsSubject.create
*	@description CRUD ACTION create
*
* actionsSubject.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsSubject.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsStudent.findBy_subject
*	@description CRUD ACTION findBy_subject
*	@param Objectid key - Id of model to search for
*
* actionsProfessor.findBy_subject
*	@description CRUD ACTION findBy_subject
*	@param Objectid key - Id of model to search for
*
* actionsSemester.findBysemester
*	@description CRUD ACTION findBysemester
*	@param Objectid key - Id of model to search for
*
* actionsSemester.list
*	@description CRUD ACTION list
*
* actionsBranch.list
*	@description CRUD ACTION list
*
* actionsProfessor.list
*	@description CRUD ACTION list
*

**/


class SubjectEdit extends Component {
  
  // Init subject
  constructor(props) {
    super(props);
    this.state = {
      subject: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsSubject.loadSubject(itemId);
        this.props.actionsStudent.findBy_subject(itemId);
        this.props.actionsProfessor.findBy_subject(itemId);
        this.props.actionsSemester.findBysemester(itemId);
      } else {
        this.setState({
          subject: {}
        });
      }
      
      this.props.actionsBranch.loadBranchList();
      this.props.actionsProfessor.loadProfessorList();
      this.props.actionsSemester.loadSemesterList();
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      subject: {}
    });
    this.props.actionsSubject.reset();
  }

  // Insert props subject in state
  componentWillReceiveProps(props) {
    this.setState({
      subject: props.subject
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.subject._id) {
      // Edit
      this.props.actionsSubject.saveSubject(this.state.subject).then(data => {
        this.props.navigation.navigate("SubjectList");
      });
    } else {
      // Create
      this.props.actionsSubject.createSubject(this.state.subject).then(data => {
        this.props.navigation.navigate("SubjectList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Subject</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel>
              <Label>
                Name
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.subject, { name: value }))
                }
                value={this.state.subject.name && this.state.subject.name.toString()}
              />
            </Item>
          
            
            <Item floatingLabel>
              <Label>
                Sub_id
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.subject, { sub_id: value }))
                }
                value={this.state.subject.sub_id && this.state.subject.sub_id.toString()}
              />
            </Item>
          

          {/* RELATIONS */}
          
          {/* Relation m:m branch with Branch */}
          
          <Item stackedLabel>              
            <Label >
              Branch
            </Label>
            <SectionedMultiSelect
              items={this.props.listBranch }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.subject, { branch: value }))
              }
              selectedItems={this.state.subject.branch }
            />
          </Item>
          
          
          {/* Relation m:m professor with professor */}
          
          <Item stackedLabel>              
            <Label >
              Professor
            </Label>
            <SectionedMultiSelect
              items={this.props.listProfessor }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.subject, { professor: value }))
              }
              selectedItems={this.state.subject.professor }
            />
          </Item>
          
          
          {/* Relation m:m semester with Semester */}
          
          <Item stackedLabel>              
            <Label >
              Semester
            </Label>
            <SectionedMultiSelect
              items={this.props.listSemester }
              displayKey="_id"
              uniqueKey="_id"
              selectText="Choose some items..."
              alwaysShowSelectText={true}
              modalAnimationType={"slide"}
              renderSelectText={() => {
                return "Choose some items...";
              }}
              onSelectedItemsChange={value =>
                this.setState(Object.assign(this.state.subject, { semester: value }))
              }
              selectedItems={this.state.subject.semester }
            />
          </Item>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Student */}

          
          {/* External relation with professor */}

          
          {/* External relation with Semester */}

          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsSubject: bindActionCreators(SubjectActions, dispatch),
    actionsStudent: bindActionCreators(StudentActions, dispatch),
    actionsProfessor: bindActionCreators(ProfessorActions, dispatch),
    actionsSemester: bindActionCreators(SemesterActions, dispatch),
    actionsBranch: bindActionCreators(BranchActions, dispatch),
  };
};

// Validate types
SubjectEdit.propTypes = { 
  actionsSubject: PropTypes.object.isRequired,
  actionsStudent: PropTypes.object.isRequired,
  actionsProfessor: PropTypes.object.isRequired,
  actionsSemester: PropTypes.object.isRequired,
  actionsBranch: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    subject: state.SubjectEditReducer.subject,
    listBranch: state.SubjectEditReducer.listBranch,
    listProfessor: state.SubjectEditReducer.listProfessor,
    listSemester: state.SubjectEditReducer.listSemester,
    listStudent: state.SubjectEditReducer.listStudent,
    listProfessor: state.SubjectEditReducer.listProfessor,
    listSemester: state.SubjectEditReducer.listSemester
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SubjectEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
